name: Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        echo "Dependencies installed successfully."
    - name: Run tests
      run: |
        echo "Starting tests..."
        pytest ./tests/unit.py
        echo "Tests completed."
      
    - name: Start the server
      run: |
        echo "Starting the server..."
        uvicorn vlite.server:app --host 0.0.0.0 --port 8000 &
        sleep 5  # Wait for the server to start
