name: Run Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        print("Dependencies installed successfully.")
    - name: Run tests
      run: |
        print("Starting tests...")
        python ./tests/unit.py
        print("Tests completed.")
